name: Build and Test (Develop)

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    name: Build and Test for Linux and macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.22]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Build for ${{ matrix.os }}
        env:
          GOOS: ${{ matrix.os == 'ubuntu-latest' && 'linux' || 'darwin' }}
          GOARCH: amd64
        run: |
          go build -o gonet-${GOOS}-${GOARCH}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gonet-${GOOS}-${GOARCH}
          path: gonet-${GOOS}-${GOARCH}

      - name: Run Tests
        run: |
          go test ./... -v

      - name: Create Release Candidate Tag
        run: |
          TAG_NAME="gonet-rc-${{ github.run_number }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "gonet-rc-${{ github.run_number }}"
          name: "Release Candidate gonet-rc-${{ github.run_number }}"
          files: |
            gonet-linux-amd64
            gonet-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
